version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sapi
      - ${SSH_AUTH_SOCK}:/ssh-agent
    ports:
      - "3000:3000"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    env_file:
      - '.env'
    depends_on:
      - db
      - redis

  db:
    image: postgres:9.4
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432"
    volumes:
      - sapi_datadb:/var/lib/postgresql/data
    env_file:
      - '.env'
 
  redis:
    image: redis
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    env_file:
      - '.env'
    volumes:
      - 'sapi-redis:/data'

  sidekiq:
    build: .
    volumes:
      - .:/sapi
    links:
      - db
      - redis
    command: bundle exec sidekiq
    env_file:
       - '.env'

volumes:
  sapi_redis_data:
  sapi_datadb:
  sapi-redis:
