version: '3'
services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - ./entrypoints/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432"
    environment:
       POSTGRES_USER: postgres
       POSTGRES_HOST_AUTH_METHOD: "trust"
#    env_file:
#      - .env-ci

  nuxt:
    build: 
      context: ./rom-gs-nuxt/nuxt-frontend
      dockerfile: Dockerfile-ci
    command: bash -l -c "yarn dev"
    volumes:
      - './nuxt-frontend:/usr/src/app'
      - node_modules:/usr/src/app/node_modules
    ports:
      - '8080:8080'
    environment:
       HOST: 0.0.0.0
       RAILS_API_ENDPOINT: http://localhost:3000/v1/
       RAILS_ENDPOINT: http://localhost:3000/
       WEBSOCKET_HOST: ws://localhost:3000/v1/cable
    depends_on:
      - rails
#    env_file:
#      - .env-ci

  rails:
    build: 
      context: ./rails-api
      dockerfile: Dockerfile-ci
    command: bash -c "rm -f /railsapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - './rails-api:/railsapp'
      - bundler_gems:/usr/local/bundle
    ports:
      - '3000:3000'
    environment:
       GEF_SPATIAL_DATABASE_HOST: db
    depends_on:
      - db
      - redis
#    - webpacker
    #  - nuxt
#    env_file:
#      - .env-ci
 
  redis:
    image: redis
    ports:
      - "6379"
    env_file:
      - '.env-ci'
    volumes:
      - redis_data:/data
 
  sidekiq:
    build:
      context: ./rails-api
      dockerfile: Dockerfile-ci
    volumes:
      - ./rails-api:/railsapp
#      - bundler_gems:/usr/local/bundle
    command: /bin/bash -l -c "bundle exec sidekiq"
    depends_on:
      - db
      - redis
    env_file:
      - '.env-ci'

  #webpacker:
  #  build: ./rails-api
  #  command: ./bin/web-dev-server
  #  volumes:
  #    - './rails-api:/railsapp'
  #  ports:
  #    - '3035:3035'

volumes:
  pgdata:
  node_modules:
  redis_data:
  bundler_gems:
