development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: grip_development

test:
  adapter: test

staging:
  adapter: redis
  url: <%= "#{ Rails.application.credentials.dig(:redis, :url) }" %>
  channel_prefix: grip_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: grip_production
